# Generated by Django 3.2.7 on 2022-06-18 07:59

from django.db import migrations, models
import django.db.models.deletion
import django_dnf.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('art', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ParameterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Ключ параметра сайта',
                'verbose_name_plural': 'Ключи параметров сайтов',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('start_process', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('finish_process', models.DateTimeField(blank=True, null=True, verbose_name='Конец обработки')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Наименование')),
                ('domain', django_dnf.fields.DomainNameField(max_length=72, unique=True, verbose_name='Домен')),
                ('crawl_delay', models.IntegerField(blank=True, null=True, verbose_name='Задержка обхода')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Наименование')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('getparam', models.CharField(blank=True, max_length=63, null=True, verbose_name='Get-параметр')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='coreapp.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='coreapp.article', verbose_name='Артикул')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='coreapp.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'unique_together': {('article', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=63, verbose_name='Наименование')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Параметры товаров',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('alt', models.CharField(blank=True, max_length=63, null=True, verbose_name='Альтернативный текст')),
                ('last_processing', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней обработки')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='coreapp.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.parameterkey', verbose_name='Ключ')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.site', verbose_name='Сaйт')),
            ],
            options={
                'verbose_name': 'Параметр сайта',
                'verbose_name_plural': 'Параметры сайтов',
                'unique_together': {('key', 'value', 'site')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('imgs', models.ManyToManyField(blank=True, to='coreapp.Link', verbose_name='Изображения')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreapp.link', verbose_name='Ссылка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreapp.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreapp.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'unique_together': {('product', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Наименование')),
                ('lat', models.IntegerField(blank=True, null=True, verbose_name='Широта')),
                ('long', models.IntegerField(blank=True, null=True, verbose_name='Долгота')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='coreapp.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
                'unique_together': {('name', 'region')},
            },
        ),
    ]
