# Generated by Django 3.2.7 on 2022-05-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='link',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='coreapp.offerlink', verbose_name='Ссылка'),
        ),
    ]
