# Generated by Django 3.2.7 on 2022-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='link',
            field=models.URLField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
