# Generated by Django 3.2.7 on 2022-06-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Ключ параметра сайта',
                'verbose_name_plural': 'Ключи параметров сайтов',
            },
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='site',
            name='crawl_delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Задержка обхода'),
        ),
        migrations.AddField(
            model_name='site',
            name='finish_process',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец обработки'),
        ),
        migrations.AddField(
            model_name='site',
            name='start_process',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('product', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('article', 'brand')},
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('link', models.URLField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('alt', models.CharField(blank=True, max_length=63, null=True, verbose_name='Альтернативный текст')),
                ('last_processing', models.DateTimeField(auto_now=True, verbose_name='Дата последней обработки')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='coreapp.site', verbose_name='Сайт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.parameterkey', verbose_name='Ключ')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.site', verbose_name='Сaйт')),
            ],
            options={
                'verbose_name': 'Параметр сайта',
                'verbose_name_plural': 'Параметры сайтов',
                'unique_together': {('key', 'value', 'site')},
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='offer',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='coreapp.Url', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreapp.url', verbose_name='Ссылка'),
        ),
        migrations.DeleteModel(
            name='ImgLink',
        ),
    ]
