# Generated by Django 3.2.7 on 2022-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20220510_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='coreapp.ImgLink', verbose_name='Изображения'),
        ),
    ]
