# Generated by Django 3.2.7 on 2022-05-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_offer_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferLink',
        ),
    ]
