# Generated by Django 3.2.7 on 2022-06-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20220510_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='site',
            name='crawl_delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Задержка обхода'),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('link', models.URLField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('cite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='coreapp.site', verbose_name='Сайт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreapp.url', verbose_name='Ссылка'),
        ),
    ]
