# Generated by Django 3.2.7 on 2022-06-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20220605_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='finish_process',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец обработки'),
        ),
        migrations.AddField(
            model_name='site',
            name='sitemap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.url', verbose_name='Sitemap'),
        ),
        migrations.AddField(
            model_name='site',
            name='start_process',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки'),
        ),
        migrations.AddField(
            model_name='url',
            name='last_processing',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней обработки'),
        ),
    ]
