# Generated by Django 3.2.7 on 2022-06-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20220605_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
