# Generated by Django 3.2.7 on 2022-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Описание'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region', 'description')},
        ),
    ]
