# Generated by Django 3.2.7 on 2022-06-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20220605_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Ключ параметра сайта',
                'verbose_name_plural': 'Ключи параметров сайтов',
            },
        ),
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=63, verbose_name='Значение')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.parameterkey', verbose_name='Ключ')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coreapp.site', verbose_name='Сaйт')),
            ],
            options={
                'verbose_name': 'Параметр сайта',
                'verbose_name_plural': 'Параметры сайтов',
                'unique_together': {('key', 'value', 'site')},
            },
        ),
    ]
