# Generated by Django 3.2.7 on 2022-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_parameterkey_siteparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterkey',
            name='title',
            field=models.CharField(max_length=63, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='siteparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
