# Generated by Django 3.2.7 on 2022-06-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_url_last_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='iterating',
            field=models.BooleanField(default=False, verbose_name='Парсить каждую страницу с разными параметрами'),
        ),
        migrations.CreateModel(
            name='GetParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=63, verbose_name='Параметр')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.shop', verbose_name='Магазин')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Get-параметры',
                'verbose_name_plural': 'Get-параметры',
                'unique_together': {('site', 'shop')},
            },
        ),
    ]
