# Generated by Django 3.2.7 on 2022-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
