# Generated by Django 3.2.7 on 2022-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='crawl_delay',
            field=models.IntegerField(default=0.5, verbose_name='Задержка обхода'),
        ),
    ]
