# Generated by Django 3.2.7 on 2022-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_shop_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст'),
        ),
    ]
